version: "3.8"

services:
  database:
    container_name: database
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=api
    ports:
      - 5432:5432
    volumes:
      - /opt/homebrew/var/postgres/data

volumes:
  db: