version: "3.8"

services:
  database:
    container_name: gdsc
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=gdsc
    ports:
      - 5432:5432
    volumes:
      - /opt/homebrew/var/postgres/data
      #If you are on windows or linux db:/var/lib/postgresql/data

volumes:
  db: