// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID         int    `json:"_id"`
	Text       string `json:"text"`
	MedicineID int    `json:"medicine_id"`
}

type Medicine struct {
	ID          int        `json:"_id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Comments    []*Comment `json:"comments,omitempty"`
}

type NewComment struct {
	Text       string `json:"text"`
	MedicineID int    `json:"medicineId"`
}

type NewMedicine struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewPost struct {
	Image  string `json:"image"`
	Text   string `json:"text"`
	Header string `json:"header"`
}

type Post struct {
	ID     int    `json:"_id"`
	Image  string `json:"image"`
	Text   string `json:"text"`
	Header string `json:"header"`
}
