// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID   string    `json:"_id"`
	Text string    `json:"text"`
	Post *Medicine `json:"post"`
}

type Medicine struct {
	ID          string     `json:"_id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Comments    []*Comment `json:"comments,omitempty"`
}

type NewComment struct {
	Text       string `json:"text"`
	MedicineID string `json:"medicineId"`
}

type NewMedicine struct {
	ID          string `json:"_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewPost struct {
	Image string `json:"image"`
	Text  string `json:"text"`
}

type Post struct {
	ID    string `json:"_id"`
	Image string `json:"image"`
	Text  string `json:"text"`
}
